laundree/laundree

public/stylesheets/promo.sass
Change promo min-width to 250px.
=> feat: Change promo min-width

routes/promo.js
=> fix: Promo title

app.js, docker-compose.yml, routes/javascripts.js
Refactor JavasScript route.
Add docker-compose file
Caching and pre-compiling javascript.
=> feat: Refactoring

public/stylesheets/index.sass
=> feat: Add spacing

views/layout.hbs
=> fix: Add and

public/stylesheets/_main.sass, public/stylesheets/sign-up.sass, views/layout.hbs, views/sign-up.hbs
Add invite step to sign-up flow.
=> feat: Add invite step

.travis.yml, docker-compose.test.yml
Add sut service in docker-compose.
=> fix: Add sut in docker-compose

Dockerfile, config.js, gulpfile.js, tests/unit/handlers/user.spec.js
Should now send coverage to code climate
Is defining env vars in docker file.
=> feat: Sending coverage and defining env

app.js, client/index.js, client/initializers/dropdown.js, client/initializers/index.js, models/user.js, package.json, public/stylesheets/_main.sass, routes/home.js, routes/index.js, views/layout.hbs
=> feat: Add login

handlers/user.js
Correctly create user on first login (set right latest provider).
=> fix: Correctly create user

.travis.yml, gulpfile.js, handlers/user.js, tests/api/controllers/users.spec.js, tests/handlers/user.spec.js, tests/utils/password.spec.js, tests/utils/validate_type.spec.js, travis.sh
Increase timeout for api tests to 20 sec.
Add test for password.
=> fix: Increase timeout and add password tests

client/decorators/form.js, handlers/user.js, package.json, tests/utils/identicon.spec.js, utils/identicon.js, utils/index.js, utils/password.js
Use identicon for generating avatars for local users.
Closes #38
=> feat: Use identicon

client/decorators/form.js, public/stylesheets/_main.sass
=> fix: Minor fixes

client/decorators/form.js, client/initializers/sign_up.js, tests/utils/validate_type.spec.js, utils/regex.js, utils/validate_type.js, views/log-in.hbs, views/sign-up.hbs
Add error-based validation for more informative error messages.
Closes #52
=> feat: Add better validation

app.js
Add error trigger for showing off new fancy error page.
=> feat: Add error trigger

app.js, setups/swagger.js
Enable error pages again by resolving promise correctly.
Closing #92
=> fix: Enable error-pages

README.md
Add system requirements section to readme file
=> chore: Add system requirements

api/controllers/machines.js, public/stylesheets/_home.sass, public/stylesheets/_laundry.sass, public/stylesheets/_main.sass, react/views/app.jsx, react/views/auth.jsx, react/views/machines.jsx
Fix style issue
Add autosave
Closes #116
=> feat: Style issues and stuff

app.js, config/default.yaml, config/production.yaml, public/stylesheets/_laundry.sass, react/views/create_laundry.jsx
Compile sass in production
Closes #107
=> feat: Compile style

client/initializers/app.jsx, lib/socket_io.js, react/views/machines.jsx, redux/index.js
=> feat: Convert init to events

react/views/timetable_headers.jsx, tests/utils/string.spec.js, utils/string.js
=> feat: Implement short name

public/stylesheets/_app.sass, react/views/timetable.jsx
=> feat: Add timetable loader

api/controllers/bookings.js, handlers/booking.js, public/stylesheets/_app.sass, public/stylesheets/_main.sass, react/views/timetable.jsx, tests/api/controllers/bookings.spec.js, views/partials/head.hbs
=> feat: Merge adjacent bookings

react/views/timetable_tables.jsx
=> fix: display edge bookings correctly

public/stylesheets/_bookings.sass, react/views/bookings.jsx, react/views/machines.jsx, redux/reducer/user_bookings.js
* Add loader
* Add document title
* Add modal
=> feat: Misc

api/controllers/bookings.js, tests/api/controllers/bookings.spec.js, tests/db_utils.js
=> feat: Add limit on earliest booking time.

app.js, react/routes/app.jsx, react/views/timetable.jsx
Add 404 for not found laundries and settings that should not be available.
Closes #179, Closes #163
=> feat: Add 404 pages

public/stylesheets/_main.sass
Clip laundry title when too long
Closes #180
=> fix: Clip header

client/api/user.js, client/initializers/app.jsx, config/default.yaml, lib/passport.js, public/stylesheets/_main.sass, react/containers/index.js, react/routes/app.jsx, react/views/home.jsx, react/views/index.js, react/views/login.jsx, react/views/verification.jsx, utils/flash.js, utils/index.js, utils/mail.js
=> feat: Allow resend verification link feature

public/stylesheets/_privacy.sass, public/stylesheets/style.sass, react/containers/index.js, react/privacy.jsx, react/routes/app.jsx, react/terms_and_conditions.jsx, react/views/index.js, react/views/login.jsx, react/views/sign_up.jsx
=> feat: Draft initial privacy policy and toc

react/views/bookings.jsx
Not opening too many modals when deleting bookings.
=> fix: Open too many modals

public/stylesheets/_bookings.sass, react/views/bookings.jsx
=> fix: Cutting items

package.json
Correct links to bug tracker and homepage.
=> fix: Correct links

api/controllers/laundries.js, email-templates/invite-user/html.hbs, email-templates/invite-user/style.scss, email-templates/invite-user/subject.hbs, email-templates/invite-user/text.hbs, email-templates/invite/html.hbs, email-templates/invite/style.scss, email-templates/invite/subject.hbs, email-templates/invite/text.hbs, email-templates/password-reset/style.sass, email-templates/password-reset/style.scss, email-templates/verify-email/style.sass, email-templates/verify-email/style.scss, handlers/laundry.js
Send verification email to users when
invited to a laundry.
Closes #169
=> feat: Send verification email

api/controllers/invites.js, api/swagger/swagger.yaml, client/api/index.js, client/api/invite.js, client/initializers/app.jsx, handlers/laundry.js, handlers/laundry_invitation.js, react/views/users.jsx, stylesheets/_users.sass, tests/api/controllers/bookings.spec.js, tests/api/controllers/invites.spec.js, tests/db_utils.js
Delete invitations to laundries
Closes #170
=> feat: Delete invitations

email-templates/invite-user/subject.hbs, email-templates/invite/subject.hbs
=> fix: Not escaping subject

gulpfile.js, package.json, routes/javascripts.js
Build client js on install. Serve if production
Closes #160
=> feat: Build JS

react/routes/app.jsx, react/views/dropdown.jsx, react/views/machines.jsx, react/views/topnav.jsx, stylesheets/_app.sass, stylesheets/_laundry.sass, stylesheets/_main.sass, stylesheets/_topnav.sass, stylesheets/style.sass
* Create DropDown Elements
* Isolate and unify DropDown styles
Closes #176
=> feat: Refactor drop-downs

react/views/leftnav.jsx, stylesheets/_main.sass
Auto-close and remove link labels.
They were stupid anyways..
=> feat: Auto-close leftnav

models/index.js
=> fix: Reconnect mongoose

react/views/timetable_headers.jsx, stylesheets/_app.sass
=> feat: Alternate between short and long names

app.js, config/custom-environment-variables.yaml, config/default.yaml, lib/opbeat.js, lib/swagger.js, package.json, travis.sh, utils/error.js
=> feat Integrate with opbeat

handlers/booking.js, handlers/handler.js, lib/socket_io.js, models/booking.js
Laundry id added to bookings
Created db update strategy
Secure sockets
Closes #174
=> feat: Add laundry id to booking and secure sockets

config/default.yaml, config/test.yaml, email-templates/invite-user/html.hbs, email-templates/invite-user/text.hbs, package.json, tests/api/controllers/users.spec.js, tests/utils/mail.spec.js, utils/mail.js
=> fix: Mail template

email-templates/contact/html.hbs, email-templates/contact/text.hbs, email-templates/support/html.hbs, email-templates/support/text.hbs
=> fix: Add sender info to mails

api/swagger/swagger.yaml, handlers/user.js, tests/api/controllers/users.spec.js
=> fix: Wrong date/date-time spec

api/controllers/laundries.js, api/swagger/swagger.yaml, client/index.js, client/sdk/laundry.js, handlers/laundry.js, handlers/user.js, lib/passport.js, models/laundry.js, models/user.js, package.json, routes/javascripts.js, tests/api/controllers/laundries.spec.js, utils/api.js, utils/password.js
=> feat: Add Demo backend

api/controllers/laundries.js, react/views/laundry_settings.jsx, stylesheets/_main.sass, tests/api/controllers/laundries.spec.js
=> feat: Remove delete button

handlers/event.js, handlers/handler.js, handlers/laundry.js, handlers/user.js, lib/swagger.js, models/event.js, models/user.js, tests/api/controllers/bookings.spec.js, tests/api/controllers/laundries.spec.js, tests/handlers/event.spec.js
Now tracking user on API and supporting custom handler data.
Closes #276
=> feat: Add custom data and user tracking

handlers/handler.js, handlers/laundry.js, handlers/user.js, lib/socket_io.js, react/views/admin_panel.jsx, stylesheets/_admin_panel.sass
Add event data to:
* UserHandler
* LaundryHandler
Add stats
* Demo user stats
* Demo laundry stats
See #275
=> feat: Add event data and stats

lib/socket_io.js
* Preventing leak on userUpdateEmitter
* Updating user rooms correctly
* Refactoring
Closes #281
=> fix: Listener-leak and room update

api/controllers/users.js, tests/unit/utils/mail.spec.js
=> fix: Add displayName to emails

lib/socket_io.js, package.json, react/containers/admin_panel.js, react/views/admin_panel.jsx, redux/actions/index.js, redux/reducer/index.js, redux/reducer/laundry_list.js, redux/reducer/laundry_list_size.js, redux/reducer/list.js, redux/reducer/singleton.js, redux/reducer/user_list.js, redux/reducer/user_list_size.js, stylesheets/_admin_panel.sass
Add user lookup and limit results on Admin panel
Closes #275
=> feat: Add user lookup and limit results

react/views/admin_panel.jsx
Wrong total pages when #%10 = 0
=> fix: Wrong total page

locales/da.json, locales/en.json, react/views/dropdown.jsx, react/views/timetable_headers.jsx, stylesheets/_app.sass
=> feat: New timetable navigation

react/views/timetable_headers.jsx, stylesheets/_app.sass
=> feat: Add arrows for navigation

react/containers/bookings.js, react/views/bookings.jsx, react/views/timetable.jsx
=> fix: Show correct booking times for Bookings and Booking modal

.gitignore, app.js, lib/passport.js, lib/session.js, locales/da.json, locales/en.json, react/containers/app.js, react/views/app.jsx, react/views/topnav.jsx, redux/index.js, routes/app.jsx, routes/index.js, scripts/travis.sh, tests/e2e/auth/login.tests.js, tests/e2e/laundry/create.tests.js, tests/e2e/laundry/machines.spec.js, tests/e2e/laundry/settings.tests.js, tests/e2e/laundry/user.tests.js, tests/e2e/locale/locate.tests.js, tests/e2e/smoke.tests.js, tests/nightwatch_utils.js
Decide if user is returning, then show login rather than sign-up.
=> feat: Add user tracking

package.json
Closes #462
https://greenkeeper.io/
=> fix(package): update laundree-sdk to version 0.0.22

package.json
Closes #452
https://greenkeeper.io/
=> chore(package): update faker to version 4.1.0

api/controllers/laundries.js
=> fix: Passing display name

package.json
Closes #480, #477 
https://greenkeeper.io/
=> fix(package): update redux-actions to version 2.0.1

.gitignore, handlers/handler.js, handlers/token.js, handlers/user.js, lib/redis.js, tests/unit/api/controllers/tokens.spec.js, tests/unit/api/controllers/users.spec.js, tests/unit/handlers/user.spec.js
=> feat: Add v2 of tokens.

handlers/laundry.js, routes/invite-code.js, tests/unit/handlers/laundries.spec.js
=> fix: Can not add demo user to laundry

api/controllers/bookings.js, handlers/booking.js, react/views/TopNav.js, stylesheets/_topnav.sass, tests/e2e/auth/login.tests.js, tests/e2e/laundry/machines.spec.js, tests/e2e/locale/locate.tests.js, tests/e2e/smoke.tests.js, tests/nightwatch_utils.js
Use update strategy rather than delete and create on merging bookings.
=> feat: Change booking strategy

handlers/user.js, lib/passport.js
Fetching 200x200 from providers
Closes #103
=> feat: Fetching larger profile pictures

client/initializers/app.js, package.json, react/containers/GAWrapper.js, react/views/App.js, react/views/GAWrapper.js, templates/partials/head.hbs, templates/web/app.hbs
=> fix: Add more GA logging

package-lock.json, src/handlers/laundry.js, src/handlers/laundry_invitation.js, src/handlers/user.js, test/unit/handlers/user.spec.js
=> fix: Mark invitations unused upon new invite
